steps:
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '--no-cache'
      - '-t'
      - 'gcr.io/${PROJECT_ID}/n8n-claira:${SHORT_SHA}'
      - '-t'
      - 'gcr.io/${PROJECT_ID}/n8n-claira:latest'
      - '.'

images:
  - 'gcr.io/${PROJECT_ID}/n8n-claira:${SHORT_SHA}'
  - 'gcr.io/${PROJECT_ID}/n8n-claira:latest'
