steps:
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '--no-cache'
      - '--pull'
      - '-t'
      - '${_IMAGE_NAME}'
      - '.'

images:
  - '${_IMAGE_NAME}'

substitutions:
  _IMAGE_NAME: 'gcr.io/${PROJECT_ID}/n8n-claira'
